dist: xenial
language: python

python:
    - "3.6"

services:
  - xvfb

before_install:
  - "export DISPLAY=:99.0"
  - sudo apt-get install gfortran libblas-dev liblapack-dev

install:
  - pip install .
  - pip install pytest

script:
  - pytest ./tests/

# notification settings
notifications:
    email:
        recipients:
            - steve.a.mattis@gmail.com
        on_success: change
        on_failure: always

# whitelist
branches:
    only:
        - master
